FROM golang:1.24.2-alpine AS builder

WORKDIR /app
COPY . .
RUN go build -o /app/marketplaceservice ./cmd

FROM alpine:latest
WORKDIR /app

RUN mkdir -p /app/config

COPY --from=builder /app/marketplaceservice .
COPY --from=builder /app/config/dev.yml /app/config/dev.yml

EXPOSE 8080
CMD ["./marketplaceservice"]