CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    ROLE VARCHAR(16) DEFAULT 'USER'
);


CREATE TABLE IF NOT EXISTS ADVERTISEMENT(
    ID SERIAL PRIMARY KEY,
    HEADER VARCHAR(64) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    IMAGE_URL VARCHAR(256) NOT NULL,
    PRICE int not NULL,
    OWNER_ID INT REFERENCES USERS(ID) NOT NULL
);